Config = {}

Config.PenalCodes = {
    ["1.1 Disorderly Conduct"] = { jailMinutes = 30, fine = 250, type = "misdemeanor" },
    ["1.2 Running Into Police Vehicle"] = { jailMinutes = 45, fine = 600, type = "misdemeanor" },
    ["1.3 Running Into Sheriff Vehicle"] = { jailMinutes = 45, fine = 600, type = "misdemeanor" },
    ["1.4 Running Into DFA Vehicle"] = { jailMinutes = 45, fine = 600, type = "misdemeanor" },
    ["1.5 Damage to State Property"] = { jailMinutes = 60, fine = 1200, type = "misdemeanor" },
    ["1.6 Stolen Vehicle (Joyriding)"] = { jailMinutes = 90, fine = 1500, type = "misdemeanor" },
    ["1.7 Traffic Infraction"] = { jailMinutes = 30, fine = 200, type = "misdemeanor" },
    ["1.8 DWI (Driving While Intoxicated)"] = { jailMinutes = 120, fine = 2000, type = "misdemeanor" },
    ["1.9 Fail to Show ID"] = { jailMinutes = 60, fine = 500, type = "misdemeanor" },
    ["1.10 No Weapon License"] = { jailMinutes = 60, fine = 1000, type = "misdemeanor" },
    ["1.11 Petty Theft"] = { jailMinutes = 45, fine = 500, type = "misdemeanor" },
    ["1.12 Evading Police"] = { jailMinutes = 60, fine = 1200, type = "misdemeanor" },
    ["1.13 Drug Possession (State)"] = { jailMinutes = 90, fine = 800, type = "misdemeanor" },
    ["1.14 Drug Possession (Federal)"] = { jailMinutes = 2880, fine = 5000, type = "felony", federal = true },
    ["1.15 Drug Trafficking (State)"] = { jailMinutes = 1440, fine = 10000, type = "felony" },
    ["1.16 Drug Trafficking (Federal)"] = { jailMinutes = 7200, fine = 25000, type = "felony", federal = true },
    ["1.17 Drug Distribution (Federal)"] = { jailMinutes = 14400, fine = 50000, type = "felony", federal = true },
    ["1.18 Weapon Possession (State)"] = { jailMinutes = 120, fine = 1200, type = "misdemeanor" },
    ["1.19 Weapon Possession (Federal)"] = { jailMinutes = 2880, fine = 5000, type = "felony", federal = true },
    ["1.20 Illegal Weapons Sales (State)"] = { jailMinutes = 1440, fine = 10000, type = "felony" },
    ["1.21 Illegal Weapons Sales (Federal)"] = { jailMinutes = 7200, fine = 25000, type = "felony", federal = true },
    ["1.22 Weapons Trafficking (Federal)"] = { jailMinutes = 14400, fine = 50000, type = "felony", federal = true },
    ["2.1 Capture of State Institutions"] = { jailMinutes = 28800, fine = 50000, type = "felony" },
    ["2.2 Taking Power by Force"] = { jailMinutes = 28800, fine = 50000, type = "felony" },
    ["2.3 Taking Hostages or Kidnapping"] = { jailMinutes = 7200, fine = 20000, type = "felony" },
    ["2.4 Fatal Collision with a Pedestrian"] = { jailMinutes = 2880, fine = 10000, type = "felony" },
    ["2.5 Attempted Theft"] = { jailMinutes = 60, fine = 800, type = "misdemeanor" },
    ["2.6 Robbery of a Police Officer"] = { jailMinutes = 7200, fine = 25000, type = "felony" },
    ["2.7 Uncoordinated Entry onto Protected Territory"] = { jailMinutes = 360, fine = 2000, type = "felony" },
    ["2.8 Collision with a Pedestrian"] = { jailMinutes = 60, fine = 1500, type = "misdemeanor" },
    ["2.9 Discharging a Weapon in a Public Place"] = { jailMinutes = 240, fine = 3000, type = "felony" },
    ["2.10 Bribing a Police Officer"] = { jailMinutes = 1440, fine = 10000, type = "felony" },
    ["2.11 Murder of a Civilian or Police Officer"] = { jailMinutes = 7200, fine = 20000, type = "felony" },
    ["2.12 Assault on a Police Officer (Hitting)"] = { jailMinutes = 1440, fine = 5000, type = "felony" },
    ["3.1 Grand Theft Auto"] = { jailMinutes = 360, fine = 2500, type = "felony" },
    ["3.2 Assault"] = { jailMinutes = 480, fine = 1500, type = "felony" },
    ["3.3 Attempted Murder"] = { jailMinutes = 1440, fine = 5000, type = "felony" },
    ["3.4 Murder"] = { jailMinutes = 7200, fine = 10000, type = "felony", minJailMinutes = 7200, maxJailMinutes = 14400 },
    ["3.5 RICO (Racketeer Influenced and Corrupt Organizations)"] = { jailMinutes = 28800, fine = 25000, type = "federal", federal = true },
    ["3.6 Corruption (State)"] = { jailMinutes = 720, fine = 5000, type = "felony" },
    ["3.7 Corruption (Federal)"] = { jailMinutes = 28800, fine = 25000, type = "federal", federal = true },
    ["3.8 Other (Felony)"] = { jailMinutes = 360, fine = 1000, type = "felony" },
    ["4.1 Damage to State Property"] = { jailMinutes = 60, fine = 1200, type = "misdemeanor" },
    ["4.2 Harm or Damage to Private Property"] = { jailMinutes = 60, fine = 1000, type = "misdemeanor" },
    ["4.3 False Calls to Police/Emergency Services"] = { jailMinutes = 30, fine = 800, type = "misdemeanor" },
    ["4.4 Debauchery (Music/Spitting/etc.)"] = { jailMinutes = 30, fine = 500, type = "misdemeanor" },
    ["4.5 Murder Threats, Murder"] = { jailMinutes = 7200, fine = 15000, type = "felony" },
    ["4.6 Insulting a State Employee"] = { jailMinutes = 30, fine = 500, type = "misdemeanor" },
    ["4.7 Extortion"] = { jailMinutes = 1440, fine = 5000, type = "felony" },
    ["5.1 Resisting Arrest"] = { jailMinutes = 25, fine = 500, type = "misdemeanor" },
    ["5.2 Disobeying a Police Officer"] = { jailMinutes = 25, fine = 500, type = "misdemeanor" },
    ["5.3 Aiding the Resisting of Arrest"] = { jailMinutes = 25, fine = 500, type = "misdemeanor" },
    ["5.4 Violation of Traffic Rules"] = { jailMinutes = 25, fine = 200, type = "misdemeanor" },
    ["5.5 Assault on a Civilian (Hitting)"] = { jailMinutes = 25, fine = 500, type = "misdemeanor" },
    ["5.6 Refusal to Present Documents"] = { jailMinutes = 25, fine = 300, type = "misdemeanor" },
}

Config.RPRules = {
    "No RDM (Random Deathmatch)",
    "No VDM (Vehicle Deathmatch)",
    "No Metagaming",
    "No Powergaming",
    "Respect all players",
    "Follow server laws and police orders",
}
